language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libboost-test-dev
      - valgrind

before_install:
  - git clone https://github.com/breakfastquay/bqvec && ( cd bqvec ; make )
  
script:
  - ./build/run-platform-tests.sh "$TRAVIS_OS_NAME"

